targets:
  - name: Qure
    description: Quantumult X Policy Icon Set
    repo: Koolson/Qure
    branch: master
  - name: Qure-Color
    description: Quantumult X Policy Icon Set (Color)
    repo: Koolson/Qure
    branch: master
    regex: "IconSet/Color.*"
  - name: Orz-3-mini
    description: By Orz-3
    repo: Orz-3/mini
    branch: master
  - name: Orz-3-mini-Alpha
    description: By Orz-3 (only alpha icons)
    repo: Orz-3/mini
    branch: master
    regex: "Alpha/.*"
  - name: Orz-3-mini-Color
    description: By Orz-3 (only color icons)
    repo: Orz-3/mini
    branch: master
    regex: "Color/.*"
